name: Reusable Deploy

on:
  workflow_call:   # rend ce workflow appelable par dâ€™autres

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: echo "Deploying and uploading..."